var PCOBJCI = 0;
var PCOBJ = new Array();
var PCClass = {create: function() {return function() {this.initialize.apply(this, arguments);}}}
var TransformView = PCClass.create();
TransformView.prototype = {initialize: function(container, ci, width,height, options) {var html = '<div class="PCBox" style="width:' + width + 'px; height:' + height + 'px;">';html += '<div class="pics' + (options.Up == true ? "" :" picsleft") + '" id="PCPICS' + ci + '">';var PCIMGS_arr = PCIMGS.split("|");var PCTITLES_arr = PCTITLES.split("|");var PCLINKS_arr = PCLINKS.split("|");for(var i = 0;i < PCIMGS_arr.length;i++){
if(PCLINKS_arr[i].length > 0 && PCLINKS_arr[i] != '#'){
	html += '<span><a href="' + PCLINKS_arr[i] + '" target="_blank"><img style="width:' + width + 'px; height:' + height + 'px;" src="' + PCIMGS_arr[i] + '" /></a></span>';
}else{
	html += '<span><img style="width:' + width + 'px; height:' + height + 'px;" src="' + PCIMGS_arr[i] + '" /></span>';
}
	}html += '</div>';html += '<ul class="num" id="PCNUM' + ci + '">';for(var i = 0;i < PCIMGS_arr.length;i++){html += '<li>' + (i + 1) + '</li>';}html += '</ul>';html += '</div>';this.$(container).innerHTML = html;var parameter = options.Up == true ? height :width;this.PCNUM = this.$("PCNUM" + ci).getElementsByTagName("li");var count = this.PCNUM.length;if(parameter <= 0 || count <= 0) return;var oContainer = this.$(container), oSlider = this.$("PCPICS" + ci), oThis = this;this.Each(this.PCNUM, function(o, i){o.onmouseover = function(){var oid = o.parentNode.id.replace("PCNUM","");o.className = "on";PCOBJ[oid].Auto = false;PCOBJ[oid].Index = i;PCOBJ[oid].Start();};o.onmouseout = function(){var oid = o.parentNode.id.replace("PCNUM","");o.className = "";PCOBJ[oid].Auto = true;PCOBJ[oid].Start();}});this.Index = 0;this._timer = null;this._slider = oSlider;this._parameter = parameter;this._count = count || 0;this._target = 0;this.SetOptions(options);this.Up = !!this.options.Up;this.Step = Math.abs(this.options.Step);this.Time = Math.abs(this.options.Time);this.Auto = !!this.options.Auto;this.Pause = Math.abs(this.options.Pause);this.onStart = this.options.onStart;this.onFinish = this.options.onFinish;oSlider.style.position = "absolute";oSlider.style.top = oSlider.style.left = 0;},$ : function (id) {return "string" == typeof id ? document.getElementById(id) : id;},SetOptions: function(options) {this.options = {Up:true,Step:5,Time:20,Auto:true,Pause:5000,onStart:function(){ this.Each(this.PCNUM, function(o, i){var oid = o.parentNode.id.replace("PCNUM",""); o.className = PCOBJ[oid].Index == i ? "on" : ""; }) },onFinish:function(){}};this.Extend(this.options, options || {});},Start: function() {if(this.Index < 0){this.Index = this._count - 1;} else if (this.Index >= this._count){ this.Index = 0; }this._target = -1 * this._parameter * this.Index;this.onStart();this.Move();},Move: function() {clearTimeout(this._timer);var oThis = this, style = this.Up ? "top" : "left", iNow = parseInt(this._slider.style[style]) || 0, iStep = this.GetStep(this._target, iNow);if (iStep != 0) {this._slider.style[style] = (iNow + iStep) + "px";this._timer = setTimeout(function(){ oThis.Move(); }, this.Time);} else {this._slider.style[style] = this._target + "px";this.onFinish();if (this.Auto) { this._timer = setTimeout(function(){ oThis.Index++; oThis.Start(); }, this.Pause); }}},GetStep: function(iTarget, iNow) {var iStep = (iTarget - iNow) / this.Step;if (iStep == 0) return 0;if (Math.abs(iStep) < 1) return (iStep > 0 ? 1 : -1);return iStep;},Stop: function(iTarget, iNow) {clearTimeout(this._timer);this._slider.style[this.Up ? "top" : "left"] = this._target + "px";},Each:function (list, fun){for (var i = 0, len = list.length; i < len; i++) { fun(list[i], i); }},Extend : function(destination, source) {for (var property in source) {destination[property] = source[property];}return destination;}};
function PCINIT(){PCOBJ[PCOBJCI] = new TransformView(PCIDS, PCOBJCI, PCWIDTH,PCHEIGHT, {Up: PCISUP});PCOBJ[PCOBJCI].Start();PCOBJCI++;}